import { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';
import './globals.css';

const jet = JetBrains_Mono({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'e-commerce🤞',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={`${jet.className} antialiased`}>
            <body>{children}</body>
        </html>
    );
}
